version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1
    hostname: web1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    ports:
      - "5001:5000"
      - "2222:22"

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2
    hostname: web2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3
    ports:
      - "5002:5000"
      - "2223:22"

  db1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db1
    hostname: db1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4
    ports:
      - "2224:22"

  db2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db2
    hostname: db2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5
    ports:
      - "2225:22"

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
