- hosts: all
  become: yes
  vars:
    ansible_remote_tmp: /home/webuser/.ansible/tmp
  tasks:
    - name: Asegurar que python3 está instalado
      apt:
        name: python3
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Ansible tmp directory exists with correct permissions
      file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: '0777'

- hosts: dbservers
  become: yes
  tasks:
    - name: Crear usuario 'dbuser'
      user:
        name: dbuser
        comment: Database User
        shell: /bin/bash

    - name: Instalar MongoDB
      apt:
        name: mongodb
        state: present

    - name: Copiar configuración de MongoDB
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongodb.conf

    - name: Reiniciar servicio MongoDB
      service:
        name: mongodb
        state: restarted
        enabled: yes

    - name: Inicializar replica set en el primario
      shell: |
        mongo --eval 'rs.initiate({_id: "rs0", members: [{ _id: 0, host: "db1:27017" }, { _id: 1, host: "db2:27017" }]})'
      when: ansible_hostname == "db1"

- hosts: webservers
  become: yes
  vars:
    db_hosts: "db1:27017,db2:27017"
  tasks:

    - name: Crear usuario 'webuser'
      user:
        name: webuser
        comment: Web Application User
        shell: /bin/bash

    - name: Instalar paquetes requeridos
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Instalar Flask y PyMongo
      pip:
        name:
          - flask
          - pymongo
        executable: pip3

    - name: Crear directorio de la aplicación
      file:
        path: /opt/myapp
        state: directory
        owner: webuser
        group: webuser
        mode: '0755'

    - name: Crear directorio para templates de la aplicación
      file:
        path: /opt/myapp/templates
        state: directory
        owner: webuser
        group: webuser
        mode: '0755'

    - name: Crear directorio para archivos estáticos
      file:
        path: /opt/myapp/static/images
        state: directory
        owner: webuser
        group: webuser
        mode: '0755'

    - name: Copiar imagen de fondo de la aplicación
      copy:
        src: static/images/background.jpeg
        dest: /opt/myapp/static/images/background.jpeg
        owner: webuser
        group: webuser
        mode: '0644'

    - name: Copiar código de la aplicación
      template:
        src: templates/app.py.j2
        dest: /opt/myapp/app.py
        owner: webuser
        group: webuser
        mode: '0755'

    - name: Copiar plantilla HTML de la aplicación
      copy:
        src: templates/index.html    # Sin extensión .j2
        dest: /opt/myapp/templates/index.html
        owner: webuser
        group: webuser
        mode: '0644'

    - name: Iniciar la aplicación
      become_user: webuser
      shell: nohup python3 /opt/myapp/app.py &
