---
# tasks file for ./ansible/roles/webserver
- name: Actualizar los repositorios apt
  apt:
    update_cache: yes

- name: Instalar Nginx y PHP
  apt:
    name:
      - nginx
      - php-fpm
    state: present

- name: Crear directorios necesarios
  file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: ansible
  loop:
    - html
    - logs

- name: Copiar configuración de Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reiniciar Nginx

# FIREWALL CONFIGURATION ver que onda
# - name: Instalar UFW
#   apt:
#     name: ufw
#     state: present
#     update_cache: yes

# - name: Configurar firewall
#   ufw:
#     rule: allow
#     port: "{{ nginx_listen_port }}"
#     proto: tcp
#   become: yes

# - name: Habilitar UFW
#   ufw:
#     state: enabled
#   become: yes
