---
# tasks file for ./ansible/roles/dbserver
- name: Actualizar los repositorios apt
  apt:
    update_cache: yes

- name: Instalar MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Configurar la contraseña de root de MySQL
  mysql_user:
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# FIREWALL CONFIGURATION ver que onda
# - name: Configurar firewall
#   ufw:
#     rule: allow
#     port: 3306
#     proto: tcp

# - name: Habilitar UFW
#   ufw:
#     state: enabled
