version: '3'

services:
  semaphore_db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphorepassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  semaphore:
    image: ansiblesemaphore/semaphore:latest
    ports:
      - "3000:3000"
    environment:
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB_HOST=semaphore_db
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphorepassword
      - SEMAPHORE_DB_NAME=semaphore
    volumes:
      - ../ansible:/tmp/ansible
    depends_on:
      - semaphore_db
    restart: unless-stopped

volumes:
  db_data:
